apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: valkey
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: valkey
      targetRevision: 6.2.6
      helm:
        releaseName: valkey
        valueFiles:
          - $values/helm-values/valkey.yaml
    - repoURL: https://github.com/pskim45/notiflex-platform.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: notiflex
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
