apiVersion: v1
kind: Service
metadata:
  name: notiflex-api-preview
  namespace: notiflex
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: notiflex-api
  ports:
    - name: http
      port: 80
      targetPort: http
