apiVersion: v1
kind: ServiceAccount
metadata:
  name: notiflex-api
  namespace: notiflex
  annotations:
    iam.gke.io/gcp-service-account: notiflex-sa@project-10edc337-9677-4dfc-91a.iam.gserviceaccount.com
